# Generated by Django 5.2.7 on 2025-10-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='img.jpg', upload_to='image/%Y', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=10000, verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='post',
            name='descripton',
            field=models.TextField(max_length=10000, verbose_name='Текст записи'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=10000, verbose_name='Заголовок записи'),
        ),
    ]
